name: uc13_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  video_compress: ^3.1.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.0.3
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  permission_handler: ^11.4.0
  http: ^1.3.0
  shared_preferences: ^2.0.8
  web_socket_channel: ^3.0.2
  socket_io_client: ^3.1.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets\fonts\static\RobotoMono-Regular.ttf
        - asset: assets\fonts\static\RobotoMono-Bold.ttf
          weight: 700
