name: uc13_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  socket_io_client: ^2.0.2
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  
     
    - family: RobotoMono
      fonts:
        - asset: assets\fonts\static\RobotoMono-Regular.ttf
        - asset: assets\fonts\static\RobotoMono-Bold.ttf
          weight: 700
  